openapi: 3.0.0
info:
  title: Presto Query Info
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: "1"
servers:
  - url: http://localhost:8080
    description: Presto endpoint when running locally
paths:
  /v1/query/{queryId}:
    delete:
      summary: Cancel a specific query
      description: Cancels the query identified by queryId
      parameters:
        - name: queryId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the query to cancel
      responses:
        '204':
          description: Query canceled successfully
    get:
      summary: Retrieve information about a specific query
      description: Retrieves detailed information about the query identified by queryId
      parameters:
        - name: queryId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the query to retrieve
      responses:
        '200':
          description: Detailed query information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryInfo'
        '404':
          description: Query not found
  /v1/query/{queryId}/killed:
    put:
      summary: Kill a specific query
      description: Kills the query identified by queryId with a provided message
      parameters:
        - name: queryId
          in: path
          required: true
          schema:
            type: string
          description: The ID of the query to kill
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              description: Message explaining why the query is being killed
      responses:
        '200':
          description: Query killed successfully
  /v1/query:
    get:
      summary: Returns a list of query resource information
      description: Retrieves information about all queries with the ability to filter and limit the result list using optional parameters
      parameters:
        - name: state
          in: query
          required: false
          schema:
            type: string
          description: Filter queries by state
        - name: limit
          in: query
          required: false
          schema:
            type: integer
          description: Limit the number of queries returned
      responses:
        '200':
          description: A list of queries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BasicQueryInfo'

components:
  schemas:
    BasicQueryInfo:
      type: object
      properties:
        queryId:
          type: string
          description: The ID of the query
        session:
          type: object
          description: Session information for the query
          properties:
            user:
              type: string
              description: The user who submitted the query
            source:
              type: string
              description: The source of the query
            catalog:
              type: string
              description: The catalog being queried
            schema:
              type: string
              description: The schema being queried
            transactionId:
              type: string
              description: The transaction ID
              nullable: true
        resourceGroupId:
          type: string
          nullable: true
          description: The resource group ID
        state:
          type: string
          description: The state of the query
        memoryPool:
          type: string
          description: The memory pool ID
        scheduled:
          type: boolean
          description: Whether the query is scheduled
        self:
          type: string
          format: uri
          description: The URI of the query
        query:
          type: string
          description: The query string
        queryHash:
          type: string
          description: The hash of the query
        queryStats:
          type: object
          description: Basic statistics about the query
          properties:
            createTime:
              type: string
              format: date-time
              description: The time when the query was created
            executionStartTime:
              type: string
              format: date-time
              description: The time when query execution started
            endTime:
              type: string
              format: date-time
              description: The time when the query ended
            totalTasks:
              type: integer
              description: The total number of tasks
            runningTasks:
              type: integer
              description: The number of running tasks
            completedTasks:
              type: integer
              description: The number of completed tasks
            totalDrivers:
              type: integer
              description: The total number of drivers
            queuedDrivers:
              type: integer
              description: The number of queued drivers
            runningDrivers:
              type: integer
              description: The number of running drivers
            completedDrivers:
              type: integer
              description: The number of completed drivers
            cumulativeUserMemory:
              type: string
              description: The cumulative user memory
            cumulativeTotalMemory:
              type: string
              description: The cumulative total memory
            totalScheduledTime:
              type: string
              description: The total scheduled time
            totalCpuTime:
              type: string
              description: The total CPU time
            totalBlockedTime:
              type: string
              description: The total blocked time
            rawInputDataSize:
              type: string
              description: The raw input data size
            rawInputPositions:
              type: integer
              description: The raw input positions
            processedInputDataSize:
              type: string
              description: The processed input data size
            processedInputPositions:
              type: integer
              description: The processed input positions
            outputDataSize:
              type: string
              description: The output data size
            outputPositions:
              type: integer
              description: The output positions
            writtenOutputDataSize:
              type: string
              description: The written output data size
            writtenOutputPositions:
              type: integer
              description: The written output positions
        errorType:
          type: string
          nullable: true
          description: The type of error, if any
        errorCode:
          type: string
          nullable: true
          description: The error code, if any
        failureInfo:
          type: object
          nullable: true
          description: Information about the failure, if any
          properties:
            message:
              type: string
              description: The error message
            errorLocation:
              type: string
              description: The location of the error
              nullable: true
            errorCode:
              type: string
              description: The error code
              nullable: true
        queryType:
          type: string
          nullable: true
          description: The type of the query
        warnings:
          type: array
          items:
            type: object
            description: Warnings related to the query
            properties:
              message:
                type: string
                description: The warning message
              warningCode:
                type: string
                description: The warning code
        preparedQuery:
          type: string
          nullable: true
          description: The prepared query, if any
